[project]
name = "bravura"
version = "0.1.0"
authors = ["Neclow <neil.clow@sund.ku.dk>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
ipykernel = ">=7.2.0,<8"
ipywidgets = ">=8.1.8,<9"
matplotlib = "*"
seaborn = "*"
pandas = ">=3.0.2,<4"
openpyxl = ">=3.1.5,<4"
scipy = ">=1.17.1,<2"
scikit-learn = ">=1.8.0,<2"
kmedoids = ">=0.5.4,<0.6"
pingouin = ">=0.6.1,<0.7"
r-base = ">=4.5.3,<4.6"
r-extradistr = ">=1.10.0.2,<2"
r-tidybayes = ">=3.0.7,<4"
tqdm = ">=4.67.3,<5"
r-emmeans = ">=2.0.2,<3"
r-bayestestr = ">=0.17.0,<0.18"
r-logspline = ">=2.1.22,<3"
r-bayesfactor = ">=0.9.12_4.8,<0.10"
r-report = ">=0.6.3,<0.7"

[tasks]
post_install = "bash scripts/post_install.sh"
brms_baseline_hr = "Rscript pipeline/brms/baseline_hr.R"
brms_beliefs_overview = "Rscript pipeline/brms/beliefs_overview.R"
brms_delta_hr = "Rscript pipeline/brms/delta_hr.R"
brms_delta_hr_rep = "Rscript pipeline/brms/delta_hr_replication.R"
brms_hormones = "Rscript pipeline/brms/hormones.R"
brms_latency = "Rscript pipeline/brms/latency.R"
brms_physio_cardiac = "Rscript pipeline/brms/physio_cardiac.R"
brms_physio_mv = "Rscript pipeline/brms/physio_multivariate.R"
brms_psap = "Rscript pipeline/brms/psap.R"
brms_shocks = "Rscript pipeline/brms/shocks.R"
brms_shocks_overview = "Rscript pipeline/brms/shocks_overview.R"
brms_trial_duration = "Rscript pipeline/brms/trial_duration.R"
cluster_behavior = "python -m pipeline.cluster_behavior"
cluster_behaviour = "python -m pipeline.cluster_behavior"
prepare_behavior = "python -m pipeline.prepare_behavior"
prepare_physio = "python -m pipeline.prepare_physio"
fig2_belief = "python -m plots.fig2_belief"
fig2_shocks_given = "python -m plots.fig2_shocks_given"
fig2_trial_duration = "python -m plots.fig2_trial_duration"
fig3_decision_modelling = "python -m plots.fig3_decision_modelling"
fig3_pca = "python -m plots.fig3_pca"
fig3_psap = "python -m plots.fig3_psap"
fig3_radar = "python -m plots.fig3_radar"
fig3_shock_per_cluster = "python -m plots.fig3_shock_per_cluster"
fig4_hr_baseline = "python -m plots.fig4_hr_baseline"
fig4_hr_delta = "python -m plots.fig4_hr_delta"
figS1_participants = "python -m plots.figS1_participants"
figS4_cluster_analysis = "python -m plots.figS4_cluster_analysis"
figS5_latency = "python -m plots.figS5_latency"
figS8_cardiac = "python -m plots.figS8_cardiac"

[pypi-dependencies]
statannotations = ">=0.7.2, <0.8"
